### ISSUE TITLE
Can't use webjar: with maven

### ISSUE THREAD

**Issue by priand** [alexo/wro4j#217]
I failed running a static build using maven and the jquery webjar. The goal is to run a static build consuming webjar content, without having the whole jar being included within the resulting app (<scope> should be 'compile' or 'provided').

Reference: https://groups.google.com/forum/#!topic/wro4j/evGexToGzJs

**Comment by alexo** [comment]
The project was migrated to a new location: https://github.com/wro4j/wro4j

**Comment by priand** [comment]
Ok, I opened another issue there. But I then suggest you to close this site, as this is what Google returns first.

**Comment by alexo** [comment]
I keep it opened, because there are still some of the issues and pull requests which were not migrated yet. The new location contains all the issues migrated from google code location. Also, I have notified on the mailing list, twiiter, google code project page and old github location about the migration.
